<%@ page pageEncoding="UTF-8"%>
<select  name="typeId" class="span2 js_typeId"></select>

<script>

//$("[name='channelId']").trigger("change");

/**(function(){
	var channelObj = $("[name='channelId']");
	channelObj.empty();
	<c:if test="${!hideChannelAllOptions}">
		var option={value:"0",text:"全部"};
		channelObj.append($("<option>", option));
	</c:if>
	var dataMap = Dict.propsChannel;
	for(var key in dataMap){
		var option={value:key,text:dataMap[key].name};
		channelObj.append($("<option>", option));
	}
})();**/

</script>